### PR TITLE
Made script work with virtual environments

### PR DESCRIPTION
**Pull request by sez11a**
Please test this on your system to make sure it works, but this should make the build script more portable to other environments. @brianchandotcom

### CODE REVIEW

**Comment by rdai10** [comment]
Hey @sez11a ,

When I run the script, I receive the following warning:

> The virtual environment was not created successfully because `ensurepip` is not
> available.  On Debian/Ubuntu systems, you need to install the `python3-venv`
> package using the following command.
> 
>     `apt-get install python3-venv`

Do you mind updating it to ensure whatever environment we end up using to run the script will have the dependency installed? Thanks!

**Comment by sez11a** [comment]
@rdai10 That isn't possible. We'd have to account for every operating system out there. You only got the message you got because you must be using Ubuntu. I think as a prerequisite we need to make sure people have a proper Python 3 environment installed already. 

I'd be very happy to make any other change necessary, but to use virtual environments, you must have the python virtual environment functionality installed. The [Python documentation](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/) seems to indicate it's normally part of the Python standard library, so it is strange to me that Ubuntu/Debian would split it out like that.

**Comment by rdai10** [comment]
Alright, sending it to @brianchandotcom for review at https://github.com/brianchandotcom/liferay-learn/pull/1

**Comment by sez11a** [comment]
@rdai10 Thank you!

**Comment by rdai10** [comment]
@sez11a It's been merged! Feel free to play around with it more!

**Pull request closed without merging**
